version: '3.7'

services:
  radius:
    image: ./main
    container_name: "radius-server"
    ports:
      - "1812-1813/udp"
    networks:
      - radius-network
    restart: "always"
  db:
    image: mariadb:10.9.3
    container_name: "radius-db"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /hostPath/database:/var/lib/mysql
    networks:
      - radius-network
    restart: "always"

networks:
  radius-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"